version: '3.8'

services:
  api:
    image: service:latest
    ports:
      - "8000:8000"
    command: [ "python", "run_api.py" ]
    env_file: ".env"

  chunks_consumer:
    image: service:latest
    command: [ "python", "run_chunks_consumer.py" ]
    env_file: ".env"

  rabbit_db_consumer:
    image: service:latest
    command: [ "python", "run_rabbit_db_consumer.py" ]
    env_file: ".env"

  tg_consumers:
    image: service:latest
    command: [ "python", "run_tg_consumers.py" ]
    env_file: ".env"
    volumes:
      - ${PWD}/session_name.session:/workdir/session_name.session

networks:
  default:
    name: service_network




